@node  charts
@section Using charts
@cindex Using charts
There are several different chart types in TOra, you can see them in the screenshot below (taken from Server Tuning tool).

@image{images/charts,9cm}

@subheading Piecharts

This is the most simple chart. If the chart is too small you can open a snapshot of the chart by doubleclicking it. You can also open a context menu by rightclicking it. In the context menu you can choose to print the chart as well and open a snapshot in a new window.

@subheading Linecharts & barcharts

These two charts work in the same way. The difference is that in a barchart the values are added on top of each other so you can easily see the sum of all values.

You can zoom a part of a chart by leftclicking it and dragging a selection. If a chart is currently zoomed the word @strong{Zoom} is printed in the upper left corner. You can remove the zooming by right clicking on the chart.

The snapshot feature, context menu and printing works the same for these charts as for the piechart. In the context menu you have an additional item though that is @strong{Properties}

@image{images/chartsetup,13cm}

@table @asis
@item @strong{Y-Axis}
      This part is pretty self explanatory and is used to set up the range to display on the Y-axis of the chart. 	
@item @strong{Show last value}
      Display the last sample added to the chart under the title of the chart.
@item @strong{Show axis legend}
      Display text with the range and units of the axises.
@item @strong{Show chart legend}
      Display the colors used in the chart in a legend to the right.
@item @strong{Divide chart in grids}
      How many gridlines to divide a chart into.
@end table
