@node common
@section Other common elements
@cindex Other common elements

These describe other elements that are used in several parts of the user interface.

@menu
* SGA Statement:sgastatement.
* Explain plan:explainplan.
* Getting bind parameters:gettingbindparameters.
* Object description:objectdescription.
* Memo editor:memoeditor.
@end menu
