@node invalid
@section Invalid Objects
@cindex Invalid Objects

This tool is usefull to recompile invalid objects in the database.

@image{images/invalid,15cm}

To the left you see a list of invalid objects. Select an object and the editor on right hand side will be filled with code to recreate the object, you can then fix whatever problem may be with it. Rows with errors will have red background and you can see the error in the statusbar by putting the cursor on the row. You can also refresh the list or change the active connection by the buttons in the toolbar.

@table @asis
@item @strong{Recompile all invalid}
This button will try recompiling all displayed invalid objects. Different types of objects are recompiled by callind different statements:
Index:
@verbatim
alter index <schema.index_name> rebuild
@end verbatim
Package body:
@verbatim
alter package <schema.package_name> compile body
@end verbatim
Public synonym:
@verbatim
create or replace public synonym <synonym_name> for <synonym_target>
@end verbatim
All other objects are recompiled using:
@verbatim
alter <object_type> <schema.object_name> compile
@end verbatim
@end table