@node output
@section SQL Output
@cindex SQL Output

This tool displays the output from the DBMS_OUTPUT package (For more information see the Oracle PL/SQL Supplied Packages manual).

@image{images/output,6cm}

Use this if you are running PL/SQL from the worksheet(@pxref{worksheet,SQL Worksheet}) and want to check the output. It is also used in the debugger (@pxref{debugger,PL/SQL Debugger}) but as a pane in the debugger information.

The toolbar contain the following controls.

@table @asis
@item @strong{Update}
Poll for more output immediately.
@item @strong{Clear output}
Clear the currently collected output.
@item @strong{Refresh}
The time-out to update automatically. The default value of this is configurable though the options.
@item @strong{Type of output}
You can choose if TOra should fetch output from standard oracle output or from Log4plsql module.
@end table
