
\input texinfo @c -*-texinfo-*-
@c %**start of header

@setfilename tora.info
@settitle TOra 
@c @image{images/tora_manual}
@c %**end of header

@copying
This manual is for TOra, version 2.1.2+.
@end copying

@titlepage
@title TOra
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c Output the table of the contents at the beginning.
@contents

@ifnottex
@node Top
@top TOra Manual 2.1.2+

@insertcopying

@end ifnottex

@menu
* Using the help browser: help.
* History of TOra: history.
* Getting to know your workspace: workspace.
* Available tools: tools.
* Extending TOra: extendingtora.
* Index-list:: Complete index.
@end menu

@include help.texi
@include history.texi
@include workspace.texi
@include window.texi
@include newconnection.texi
@include whatprivileges.texi
@include editors.texi
@include lists.texi
@include charts.texi
@include searchreplace.texi
@include preferences.texi
@include editor.texi
@include database.texi
@include additionalhelp.texi
@include toolsetting.texi
@include common.texi
@include sgastatement.texi
@include explainplan.texi
@include gettingbindparameters.texi
@include objectdescription.texi
@include memoeditor.texi
@include tools.texi
@include worksheet.texi
@include browser.texi
@include plsqleditor.texi
@include debugger.texi
@include unittest.texi
@include tuning.texi
@include security.texi
@include storage.texi
@include session.texi
@include rollback.texi
@include trace.texi
@include current.texi
@include script.texi
@include analyze.texi
@include alert.texi
@include invalid.texi
@include output.texi
@include template.texi
@include sqledit.texi
@include extendingtora.texi
@include api.texi
@include externalapi.texi
@node Index-list
@unnumbered Index-list
@printindex cp
@bye

