############################################################################
# $Id$
#
# Copyright (C) 2000-2001 GlobeCom AB.  All rights reserved.
#
# This file is part of the Toolkit for Oracle.
#
# This file may be distributed under the terms of the Q Public License
# as defined by Trolltech AS of Norway and appearing in the file
# LICENSE included in the packaging of this file.
#
# This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
# WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
# See http://www.globecom.net/tora/ for more information.
#
# Contact tora@globecom.se if any conditions of this licensing are
# not clear to you.
#
############################################################################

include Makefile.setup

ifeq ($(MYSQL_FOUND),1)
MYSQL_CPP=tomysqlconnection.cpp
MYSQL_PLUGIN=plugins/tomysqlconnection.tso
endif

TITLE=TOra
SUBDIRS=
SOURCES=\
	toabout.cpp 		        \
	toaboutui.cpp			\
	tobarchart.cpp		        \
	tobrowser.cpp		        \
	tobrowserconstraintui.cpp	\
	tobrowserfilterui.cpp	        \
	tobrowserindexui.cpp	        \
	toconnection.cpp	        \
	tocurrent.cpp		        \
	tochangeconnection.cpp	        \
	todatabasesettingui.cpp	        \
	todebug.cpp		        \
	todebugchange.cpp	        \
	todebugtext.cpp		        \
	todebugwatch.cpp	        \
	toextract.cpp		        \
	tofilesize.cpp		        \
	toglobalsetting.cpp             \
	toglobalsettingui.cpp	        \
	tohelp.cpp		        \
	tohelpaddfileui.cpp	        \
	tohelpsetupui.cpp	        \
	tohighlightedtext.cpp	        \
	tohtml.cpp		        \
	tolinechart.cpp		        \
	tomain.cpp		        \
	tomarkedtext.cpp	        \
	tomemoeditor.cpp	        \
	tonewconnection.cpp	        \
	tonewconnectionui.cpp	        \
	tonoblockquery.cpp	        \
	tooutput.cpp		        \
	tooracleconnection.cpp	        \
	toparamget.cpp		        \
	topiechart.cpp		        \
	topreferences.cpp	        \
	topreferencesui.cpp	        \
	toresult.cpp			\
	toresultbar.cpp		        \
	toresultcols.cpp	        \
	toresultconstraint.cpp	        \
	toresultcontent.cpp		\
	toresultcontentfilterui.cpp	\
	toresultdepend.cpp	        \
	toresultfield.cpp	        \
	toresultindexes.cpp	        \
	toresultitem.cpp	        \
	toresultline.cpp	        \
	toresultlock.cpp	        \
	toresultlong.cpp	        \
	toresultpie.cpp		        \
	toresultplan.cpp	        \
	toresultreferences.cpp	        \
	toresultstats.cpp	        \
	toresultstorage.cpp	        \
	toresultview.cpp	        \
	torollback.cpp		        \
	torollbackdialogui.cpp	        \
	toscript.cpp		        \
	toscriptui.cpp		        \
	tosearchreplace.cpp	        \
	tosearchreplaceui.cpp	        \
	tosession.cpp		        \
	tosecurity.cpp		        \
	tosecurityquotaui.cpp	        \
	tosecurityroleui.cpp	        \
	tosecurityuserui.cpp	        \
	tosgastatement.cpp	        \
	tosgatrace.cpp		        \
	tosql.cpp		        \
	tosqledit.cpp		        \
	tostorage.cpp		        \
	tostoragedatafileui.cpp	        \
	tostoragedefinition.cpp	        \
	tostoragedefinitionui.cpp       \
	tostoragedialogui.cpp		\
	tostoragetablespaceui.cpp	\
	tosyntaxsetup.cpp	        \
	tosyntaxsetupui.cpp		\
	totemplate.cpp		        \
	totemplateaddfileui.cpp	        \
	totemplateeditui.cpp	        \
	totemplateprovider.cpp	        \
	totemplatesetupui.cpp	        \
	tothread.cpp		        \
	totool.cpp			\
	totoolsettingui.cpp		\
	totuning.cpp			\
	totuningoverviewui.cpp		\
	toworksheet.cpp			\
	toworksheetsetupui.cpp		\
	utils.cpp			\
	$(MYSQL_CPP)

API=	\
	tochangeconnection.h	\
	tobarchart.h		\
	toconf.h		\
	toconnection.h		\
	todefaultkeywords.h	\
	toextract.h		\
	tofilesize.h		\
	tohelp.h		\
	tohelpbrowser.h		\
	tohighlightedtext.h	\
	tohtml.h		\
	tolinechart.h		\
	tomain.h		\
	tomainwindow.kde.h	\
	tomarkedtext.2.h	\
	tomarkedtext.h		\
	tomemoeditor.h		\
	tonoblockquery.h	\
	toparamget.h		\
	topiechart.h		\
	toresult.h		\
	toresultbar.h		\
	toresultcols.h		\
	toresultconstraint.h	\
	toresultcontent.h	\
	toresultdepend.h	\
	toresultfield.h		\
	toresultindexes.h	\
	toresultitem.h		\
	toresultline.h		\
	toresultlong.h		\
	toresultpie.h		\
	toresultplan.h		\
	toresultreferences.h	\
	toresultresources.h	\
	toresultstats.h		\
	toresultview.h		\
	tosgastatement.h	\
	tosql.h			\
	totemplate.h		\
	tothread.h		\
	totool.h

include Makefile.common

plugins/tobrowser.tso:\
	objs/tobrowser.o \
	objs/tobrowserconstraintui.o \
	objs/tobrowserfilterui.o \
	objs/tobrowserindexui.o
plugins/tocharts.tso:\
	objs/tobarchart.o \
	objs/tolinechart.o \
	objs/topiechart.o \
	objs/toresultbar.o \
	objs/toresultline.o \
	objs/toresultpie.o
plugins/todebug.tso:\
	objs/todebug.o \
	objs/todebugwatch.o \
	objs/todebugtext.o \
	objs/todebugchange.o
plugins/tocurrent.tso:objs/tocurrent.o
plugins/toextract.tso:objs/toextract.o
plugins/tofilesize.tso:objs/tofilesize.o
plugins/tooutput.tso:objs/tooutput.o
plugins/tonoblockquery.tso:objs/tonoblockquery.o
plugins/toresult.tso:\
	objs/toresultconstraint.o \
	objs/toresultdepend.o \
	objs/toresultindexes.o \
	objs/toresultlock.o \
	objs/toresultlong.o \
	objs/toresultreferences.o \
	objs/toresultstats.o \
	objs/toresultstorage.o
plugins/torollback.tso:\
	objs/torollback.o \
	objs/torollbackdialogui.o
plugins/toscript.tso:\
	objs/toscript.o \
	objs/toscriptui.o
plugins/tosession.tso:objs/tosession.o
plugins/tosecurity.tso:\
	objs/tosecurity.o \
	objs/tosecurityquotaui.o \
	objs/tosecurityroleui.o \
	objs/tosecurityuserui.o
plugins/tosgastatement.tso:objs/tosgastatement.o
plugins/tosgatrace.tso:objs/tosgatrace.o
plugins/tosqledit.tso:objs/tosqledit.o
plugins/tostorage.tso:\
	objs/tostorage.o \
	objs/tostoragedatafileui.o \
	objs/tostoragedialogui.o \
	objs/tostoragetablespaceui.o
plugins/tostoragedefinition.tso:\
	objs/tostoragedefinition.o \
	objs/tostoragedefinitionui.o
plugins/totemplate.tso:\
	objs/totemplate.o \
	objs/totemplateaddfileui.o \
	objs/totemplateeditui.o \
	objs/totemplatesetupui.o
plugins/totuning.tso:\
	objs/totuning.o \
	objs/totuningoverviewui.o
plugins/toworksheet.tso: \
	objs/toworksheet.o \
	objs/toworksheetsetupui.o

# Special plugins

plugins/tooracleconnection.tso:objs/tooracleconnection.o
	@echo Linking plugin $@
	if [ ! -d plugins ] ; then mkdir -p plugins ; fi
	$(GCC) -shared $(CFLAGS) $(LFLAGS) $(LFLAGS_GLOB) $(ORACLE_SHARED) -o $@ $^

plugins/tomysqlconnection.tso:objs/tomysqlconnection.o
	@echo Linking plugin $@
	if [ ! -d plugins ] ; then mkdir -p plugins ; fi
	$(GCC) -shared $(CFLAGS) $(LFLAGS) $(LFLAGS_GLOB) $(MYSQL_SHARED) -o $@ $^

# Monolithic target, for non ELF platforms

tora-mono: $(OBJECTS) main.cpp
	@echo Linking $@
	$(GCC) $(CFLAGS) $(LFLAGS) $(LFLAGS_GLOB) -DTOMONOLITHIC -o $@ $(OBJECTS) main.cpp \
		$(LIBS_GLOB) $(STDCPP_SHARED) $(ORACLE_SHARED) $(QT_SHARED) $(MYSQL_SHARED)

# Static target, easier to distribute

tora-static: $(OBJECTS) main.cpp
	@echo Linking $@
	$(GCC) $(LFLAGS) $(CFLAGS) $(LFLAGS_GLOB) -DTOMONOLITHIC -o $@ $(OBJECTS) main.cpp \
		$(QT_STATIC) $(STDCPP_STATIC) $(ORACLE_STATIC) $(LIBS_GLOB) $(MYSQL_STATIC) \
		/usr/X11R6/lib/libXext.a /usr/X11R6/lib/libXft.a /usr/X11R6/lib/libXrender.a \
		/usr/X11R6/lib/libX11.a /usr/X11R6/lib/libSM.a /usr/X11R6/lib/libICE.a\
		/usr/lib/libmng.a -lz -ljpeg

# Plugin based binary and its plugins

tora-plugin: \
	tora \
	plugins/tobrowser.tso \
	plugins/tocharts.tso \
	plugins/todebug.tso \
	plugins/tocurrent.tso \
	plugins/toextract.tso \
	plugins/tofilesize.tso \
	plugins/tonoblockquery.tso \
	plugins/tooutput.tso \
	plugins/tooracleconnection.tso \
	plugins/toresult.tso \
	plugins/torollback.tso \
	plugins/toscript.tso \
	plugins/tosession.tso \
	plugins/tosecurity.tso \
	plugins/tosgastatement.tso \
	plugins/tosgatrace.tso \
	plugins/tosqledit.tso \
	plugins/tostorage.tso \
	plugins/tostoragedefinition.tso \
	plugins/totemplate.tso \
	plugins/totuning.tso \
	plugins/toworksheet.tso \
	$(MYSQL_PLUGIN)

# The binary for the pluginbased tora

tora: \
	objs/main.o \
	objs/toabout.o \
	objs/toaboutui.o \
	objs/tochangeconnection.o \
	objs/toconnection.o \
	objs/todatabasesettingui.o \
	objs/toglobalsetting.o \
	objs/toglobalsettingui.o \
	objs/tohelp.o \
	objs/tohelpaddfileui.o \
	objs/tohelpsetupui.o \
	objs/tohighlightedtext.o \
	objs/tohtml.o \
	objs/tomain.o \
	objs/tomarkedtext.o \
	objs/tomemoeditor.o \
	objs/tonewconnection.o \
	objs/tonewconnectionui.o \
	objs/toparamget.o \
	objs/topreferences.o \
	objs/topreferencesui.o \
	objs/toresult.o \
	objs/toresultcols.o \
	objs/toresultcontent.o \
	objs/toresultcontentfilterui.o \
	objs/toresultfield.o \
	objs/toresultitem.o \
	objs/toresultplan.o \
	objs/toresultview.o \
	objs/tosql.o \
	objs/tosearchreplace.o \
	objs/tosearchreplaceui.o \
	objs/tosyntaxsetup.o \
	objs/tosyntaxsetupui.o \
	objs/totemplateprovider.o \
	objs/tothread.o \
	objs/totool.o \
	objs/totoolsettingui.o \
	objs/utils.o
	@echo Linking $@
	$(GCC) $(LFLAGS) -Xlinker "--export-dynamic" $(LFLAGS_GLOB) \
		-o $@ $^ $(LIBS_GLOB) $(STDCPP_SHARED) $(QT_SHARED)

# This pretty requires a kdoc installtion and reference files for Qt and KDE Libs.
# configure won't try to detect those. It's up to you.

apidoc: $(API)
	mkdir -p help/api
	kdoc -n TOra -d help/api $^ -lqt -lkdeui -lkhtml
