############################################################################
#
# TOra - An Oracle Toolkit for DBA's and developers
# Copyright (C) 2000  GlobeCom AB
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
############################################################################

TITLE=TOra
SUBDIRS=
SOURCES=\
	toabout.cpp 		\
	tobrowser.cpp		\
	toconnection.cpp	\
	todebug.cpp		\
	todebugchange.cpp	\
	todebugtext.cpp		\
	todebugwatch.cpp	\
	toextract.cpp		\
	tofilesize.cpp		\
	toglobalsetting.cpp     \
	tohighlightedtext.cpp	\
	tomain.cpp		\
	tomarkedtext.cpp	\
	tomemoeditor.cpp	\
	tonewconnection.cpp	\
	tonoblockquery.cpp	\
	tooutput.cpp		\
	toparamget.cpp		\
	topreferences.cpp	\
	toresultcols.cpp	\
	toresultconstraint.cpp	\
	toresultcontent.cpp	\
	toresultdepend.cpp	\
	toresultfield.cpp	\
	toresultindexes.cpp	\
	toresultitem.cpp	\
	toresultlock.cpp	\
	toresultlong.cpp	\
	toresultplan.cpp	\
	toresultreferences.cpp	\
	toresultstats.cpp	\
	toresultstorage.cpp	\
	toresultview.cpp	\
	torollback.cpp		\
	toscript.cpp		\
	toscriptui.cpp		\
	tosearchreplace.cpp	\
	tosearchreplaceui.cpp	\
	tosession.cpp		\
	tosecurity.cpp		\
	tosecurityquotaui.cpp	\
	tosecurityroleui.cpp	\
	tosecurityuserui.cpp	\
	tosgastatement.cpp	\
	tosgatrace.cpp		\
	tosql.cpp		\
	tosqledit.cpp		\
	tostorage.cpp		\
	tostoragedefinition.cpp	\
	tosyntaxsetup.cpp	\
	tothread.cpp		\
	totool.cpp		\
	toworksheet.cpp		\
	utils.cpp

TARGET=tora-plugin

include Makefile.setup
include Makefile.common

plugins/tobrowser.tso:objs/tobrowser.o
plugins/todebug.tso:\
	objs/todebug.o \
	objs/todebugwatch.o \
	objs/todebugtext.o \
	objs/todebugchange.o
plugins/toextract.tso:objs/toextract.o
plugins/tofilesize.tso:objs/tofilesize.o
plugins/tooutput.tso:objs/tooutput.o
plugins/tonoblockquery.tso:objs/tonoblockquery.o
plugins/toparamget.tso:objs/toparamget.o
plugins/toresultcols.tso:objs/toresultcols.o
plugins/toresultconstraint.tso:objs/toresultconstraint.o
plugins/toresultdepend.tso:objs/toresultdepend.o
plugins/toresultindexes.tso:objs/toresultindexes.o
plugins/toresultlock.tso:objs/toresultlock.o
plugins/toresultlong.tso:objs/toresultlong.o
plugins/toresultreferences.tso:objs/toresultreferences.o
plugins/toresultstats.tso:objs/toresultstats.o
plugins/toresultstorage.tso:objs/toresultstorage.o
plugins/torollback.tso:objs/torollback.o
plugins/toscript.tso:\
	objs/toscript.o \
	objs/toscriptui.o
plugins/tosession.tso:objs/tosession.o
plugins/tosecurity.tso:\
	objs/tosecurity.o \
	objs/tosecurityquotaui.o \
	objs/tosecurityroleui.o \
	objs/tosecurityuserui.o
plugins/tosgastatement.tso:objs/tosgastatement.o
plugins/tosgatrace.tso:objs/tosgatrace.o
plugins/tosqledit.tso:objs/tosqledit.o
plugins/tostorage.tso:objs/tostorage.o
plugins/tostoragedefinition.tso:objs/tostoragedefinition.o
plugins/toworksheet.tso:objs/toworksheet.o

# Monolithic target, for non ELF platforms

tora-mono: $(OBJECTS) main.cpp
	@echo Linking $@
	$(GCC) $(CFLAGS) $(LFLAGS) $(LFLAGS_GLOB) -DTOMONOLITHIC -o $@ $(OBJECTS) main.cpp \
		$(LIBS_GLOB) $(STDCPP_SHARED) $(ORACLE_SHARED) $(QT_SHARED)

# Static target, easier to distribute

tora-static: $(OBJECTS) main.cpp
	@echo Linking $@
	$(GCC) $(LFLAGS) $(CFLAGS) $(LFLAGS_GLOB) -DTOMONOLITHIC -o $@ $(OBJECTS) main.cpp \
		$(QT_STATIC) $(STDCPP_STATIC) $(ORACLE_STATIC) $(LIBS_GLOB) \
		/usr/X11R6/lib/libXext.a /usr/X11R6/lib/libXft.a /usr/X11R6/lib/libXrender.a \
		/usr/X11R6/lib/libX11.a /usr/X11R6/lib/libSM.a /usr/X11R6/lib/libICE.a\
		/usr/lib/libmng.a -lz -ljpeg

# Plugin based binary and its plugins

tora-plugin: \
	tora \
	plugins/tobrowser.tso \
	plugins/todebug.tso \
	plugins/toextract.tso \
	plugins/tofilesize.tso \
	plugins/tonoblockquery.tso \
	plugins/tooutput.tso \
	plugins/toparamget.tso \
	plugins/toresultcols.tso \
	plugins/toresultconstraint.tso \
	plugins/toresultdepend.tso \
	plugins/toresultindexes.tso \
	plugins/toresultlock.tso \
	plugins/toresultlong.tso \
	plugins/toresultreferences.tso \
	plugins/toresultstats.tso \
	plugins/toresultstorage.tso \
	plugins/torollback.tso \
	plugins/toscript.tso \
	plugins/tosession.tso \
	plugins/tosecurity.tso \
	plugins/tosgastatement.tso \
	plugins/tosgatrace.tso \
	plugins/tosqledit.tso \
	plugins/tostorage.tso \
	plugins/tostoragedefinition.tso \
	plugins/toworksheet.tso \

# The binary for the pluginbased tora

test:   objs/test.o \
	objs/test2.o
	@echo Linking $@
	$(GCC) $(LFLAGS) $(LFLAGS_GLOB) \
		-o $@ $^ $(LIBS_GLOB) $(ORACLE_SHARED) $(STDCPP_SHARED) $(QT_SHARED)

tora: \
	objs/main.o \
	objs/toabout.o \
	objs/toconnection.o \
	objs/toglobalsetting.o \
	objs/tohighlightedtext.o \
	objs/tomain.o \
	objs/tomarkedtext.o \
	objs/tomemoeditor.o \
	objs/tonewconnection.o \
	objs/topreferences.o \
	objs/toresultcontent.o \
	objs/toresultfield.o \
	objs/toresultitem.o \
	objs/toresultplan.o \
	objs/toresultview.o \
	objs/tosql.o \
	objs/tosearchreplace.o \
	objs/tosearchreplaceui.o \
	objs/tosyntaxsetup.o \
	objs/tothread.o \
	objs/totool.o \
	objs/utils.o
	@echo Linking $@
	$(GCC) $(LFLAGS) -Xlinker "--export-dynamic" $(LFLAGS_GLOB) \
		-o $@ $^ $(LIBS_GLOB) $(ORACLE_SHARED) $(STDCPP_SHARED) $(QT_SHARED)
