############################################################################
#
# TOra - An Oracle Toolkit for DBA's and developers
# Copyright (C) 2000-2001,2001 GlobeCom AB
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation;  only version 2 of
# the License is valid for this program.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#      As a special exception, you have permission to link this program
#      with the Oracle Client libraries and distribute executables, as long
#      as you follow the requirements of the GNU GPL in regard to all of the
#      software in the executable aside from Oracle client libraries. You
#      are also allowed to link this program with the Qt Non Commercial for
#      Windows.
#
#      Specifically you are not permitted to link this program with the
#      Qt/UNIX or Qt/Windows products of TrollTech. And you are not
#      permitted to distribute binaries compiled against these libraries
#      without written consent from GlobeCom AB. Observe that this does not
#      disallow linking to the Qt Free Edition.
#
# All trademarks belong to their respective owners.
#
############################################################################

include Makefile.setup

ifeq ($(MYSQL_FOUND),1)
MYSQL_CPP=tomysqlconnection.cpp
MYSQL_PLUGIN=plugins/tomysqlconnection.tso
endif

MAKEFILE_ORIG=Makefile.orig
TITLE=TOra
SUBDIRS=
SOURCES=\
	toabout.cpp 		        \
	toaboutui.cpp			\
	toalert.cpp			\
	toanalyze.cpp			\
	tobackground.cpp		\
	tobarchart.cpp		        \
	tobrowser.cpp		        \
	tobrowserconstraintui.cpp	\
	tobrowserfilterui.cpp	        \
	tobrowserindexui.cpp	        \
	tobrowsertableui.cpp	        \
	toconnection.cpp	        \
	tocurrent.cpp		        \
	tochangeconnection.cpp	        \
	todatabasesettingui.cpp	        \
	todebug.cpp		        \
	todebugchange.cpp	        \
	todebugtext.cpp		        \
	todebugwatch.cpp	        \
	toeditwidget.cpp		\
	toextract.cpp		        \
	tofilesize.cpp		        \
	toglobalsetting.cpp             \
	toglobalsettingui.cpp	        \
	tohelp.cpp		        \
	tohelpaddfileui.cpp	        \
	tohelpsetupui.cpp	        \
	tohighlightedtext.cpp	        \
	tohtml.cpp		        \
	toinvalid.cpp			\
	tolegendchart.cpp		\
	tolinechart.cpp		        \
	tolinechartsetupui.cpp		\
	tomain.cpp		        \
	tomarkedtext.cpp	        \
	tomemoeditor.cpp	        \
	tomessageui.cpp			\
	tonewconnection.cpp	        \
	tonewconnectionui.cpp	        \
	tonoblockquery.cpp	        \
	tooutput.cpp		        \
	tooracleconnection.cpp	        \
	tooraclesettingui.cpp		\
	toparamget.cpp		        \
	topiechart.cpp		        \
	topreferences.cpp	        \
	topreferencesui.cpp	        \
	toresult.cpp			\
	toresultbar.cpp		        \
	toresultcols.cpp	        \
	toresultconstraint.cpp	        \
	toresultcontent.cpp		\
	toresultcontentfilterui.cpp	\
	toresultdepend.cpp	        \
	toresultextract.cpp		\
	toresultfield.cpp	        \
	toresultindexes.cpp	        \
	toresultitem.cpp	        \
	toresultlabel.cpp		\
	toresultline.cpp	        \
	toresultlistformatui.cpp	\
	toresultlock.cpp	        \
	toresultlong.cpp	        \
	toresultparam.cpp		\
	toresultpie.cpp		        \
	toresultplan.cpp	        \
	toresultreferences.cpp	        \
	toresultstats.cpp	        \
	toresultstorage.cpp	        \
	toresultview.cpp	        \
	torollback.cpp		        \
	torollbackdialogui.cpp	        \
	toscript.cpp		        \
	toscriptui.cpp		        \
	tosearchreplace.cpp	        \
	tosearchreplaceui.cpp	        \
	tosession.cpp		        \
	tosecurity.cpp		        \
	tosecurityquotaui.cpp	        \
	tosecurityroleui.cpp	        \
	tosecurityuserui.cpp	        \
	tosgastatement.cpp	        \
	tosgatrace.cpp		        \
	tosql.cpp		        \
	tosqledit.cpp		        \
	tostorage.cpp		        \
	tostoragedatafileui.cpp	        \
	tostoragedefinition.cpp	        \
	tostoragedefinitionui.cpp       \
	tostoragedialogui.cpp		\
	tostoragetablespaceui.cpp	\
	tosyntaxsetup.cpp	        \
	tosyntaxsetupui.cpp		\
	totemplate.cpp		        \
	totemplateaddfileui.cpp	        \
	totemplateeditui.cpp	        \
	totemplateprovider.cpp	        \
	totemplatesetupui.cpp	        \
	tothread.cpp		        \
	totool.cpp			\
	totoolsettingui.cpp		\
	totuning.cpp			\
	totuningoverviewui.cpp		\
	totuningsettingui.cpp		\
	tovisualize.cpp			\
	toworksheet.cpp			\
	toworksheetsetupui.cpp		\
	toworksheetstatistic.cpp	\
	utils.cpp			\
	$(MYSQL_CPP)

API=	\
	tochangeconnection.h	\
	tobackground.h		\
	tobarchart.h		\
	toconf.h		\
	toconnection.h		\
	todefaultkeywords.h	\
	toeditwidget.h		\
	toextract.h		\
	tofilesize.h		\
	tohelp.h		\
	tohelpbrowser.h		\
	tohighlightedtext.h	\
	tohtml.h		\
	tolinechart.h		\
	tomain.h		\
	tomainwindow.kde.h	\
	tomarkedtext.2.h	\
	tomarkedtext.h		\
	tomemoeditor.h		\
	tonoblockquery.h	\
	toparamget.h		\
	topiechart.h		\
	toqvalue.h		\
	toresult.h		\
	toresultbar.h		\
	toresultcols.h		\
	toresultconstraint.h	\
	toresultcontent.h	\
	toresultdepend.h	\
	toresultfield.h		\
	toresultindexes.h	\
	toresultitem.h		\
	toresultlabel.h		\
	toresultline.h		\
	toresultlong.h		\
	toresultpie.h		\
	toresultplan.h		\
	toresultreferences.h	\
	toresultresources.h	\
	toresultstats.h		\
	toresultview.h		\
	tosgastatement.h	\
	tosql.h			\
	totemplate.h		\
	tothread.h		\
	totool.h		\
	tovisualize.h

default: all
include $(ORACLE_HOME)/rdbms/lib/env_rdbms.mk
include Makefile.common

plugins/toalert.tso:objs/toalert.o
plugins/toanalyze.tso:\
	objs/toanalyze.o \
	objs/toworksheetstatistic.o
plugins/tobrowser.tso:\
	objs/tobrowser.o \
	objs/tobrowserconstraintui.o \
	objs/tobrowserfilterui.o \
	objs/tobrowserindexui.o \
	objs/tobrowsertableui.o
plugins/tocharts.tso:\
	objs/tobarchart.o \
	objs/tolegendchart.o \
	objs/tolinechart.o \
	objs/tolinechartsetupui.o \
	objs/topiechart.o \
	objs/toresultbar.o \
	objs/toresultline.o \
	objs/toresultpie.o
plugins/todebug.tso:\
	objs/todebug.o \
	objs/todebugwatch.o \
	objs/todebugtext.o \
	objs/todebugchange.o
plugins/tocurrent.tso:objs/tocurrent.o
plugins/toextract.tso:\
	objs/toextract.o \
	objs/toresultextract.o
plugins/toinvalid.tso:objs/toinvalid.o
plugins/tooutput.tso:objs/tooutput.o
plugins/toresult.tso:\
	objs/toresultcols.o \
	objs/toresultconstraint.o \
	objs/toresultcontent.o \
	objs/toresultcontentfilterui.o \
	objs/toresultdepend.o \
	objs/toresultindexes.o \
	objs/toresultlabel.o \
	objs/toresultlock.o \
	objs/toresultlong.o \
	objs/toresultplan.o \
	objs/toresultparam.o \
	objs/toresultreferences.o \
	objs/toresultstorage.o
plugins/torollback.tso:\
	objs/torollback.o \
	objs/torollbackdialogui.o
plugins/toscript.tso:\
	objs/toscript.o \
	objs/toscriptui.o
plugins/tosession.tso:objs/tosession.o
plugins/tosecurity.tso:\
	objs/tosecurity.o \
	objs/tosecurityquotaui.o \
	objs/tosecurityroleui.o \
	objs/tosecurityuserui.o
plugins/tosgatrace.tso:objs/tosgatrace.o
plugins/tosqledit.tso:objs/tosqledit.o
plugins/tostorage.tso:\
	objs/tostorage.o \
	objs/tostoragedatafileui.o \
	objs/tostoragedialogui.o \
	objs/tostoragetablespaceui.o
plugins/tostoragedefinition.tso:\
	objs/tostoragedefinition.o \
	objs/tostoragedefinitionui.o
plugins/totemplate.tso:\
	objs/totemplate.o \
	objs/totemplateaddfileui.o \
	objs/totemplateeditui.o \
	objs/totemplatesetupui.o
plugins/totuning.tso:\
	objs/totuning.o \
	objs/totuningoverviewui.o \
	objs/totuningsettingui.o
plugins/towidgets.tso:\
	objs/tochangeconnection.o \
	objs/tofilesize.o \
	objs/tosgastatement.o \
	objs/tovisualize.o
plugins/toworksheet.tso:\
	objs/toworksheet.o \
	objs/toworksheetsetupui.o

# Special plugins

plugins/tooracleconnection.tso: \
	objs/tooracleconnection.o \
	objs/tooraclesettingui.o
	@echo Linking plugin $@
	if [ ! -d plugins ] ; then mkdir -p plugins ; fi
	$(GCC) -shared $(CFLAGS) $(LFLAGS) $(LFLAGS_GLOB) -o $@ $^ $(ORACLE_SHARED)

plugins/tomysqlconnection.tso:objs/tomysqlconnection.o
	@echo Linking plugin $@
	if [ ! -d plugins ] ; then mkdir -p plugins ; fi
	$(GCC) -shared $(CFLAGS) $(LFLAGS) $(LFLAGS_GLOB) $(MYSQL_SHARED) -o $@ $^

# Monolithic target, for non ELF platforms

tora-mono: $(OBJECTS) main.cpp
	@echo Linking $@
	$(GCC) $(CFLAGS) $(LFLAGS) $(LFLAGS_GLOB) -DTOMONOLITHIC -o $@ $(OBJECTS) main.cpp \
		$(LIBS_GLOB) $(STDCPP_SHARED) $(ORACLE_SHARED) $(QT_SHARED) $(MYSQL_SHARED)

# Static target, easier to distribute

tora-static: $(OBJECTS) main.cpp
	@echo Linking $@
	$(GCC) $(LFLAGS) $(CFLAGS) $(LFLAGS_GLOB) -DTOMONOLITHIC -o $@ $(OBJECTS) main.cpp \
		$(QT_STATIC) $(STDCPP_STATIC) $(ORACLE_STATIC) $(LIBS_GLOB) $(MYSQL_STATIC) \
		/usr/X11R6/lib/libXext.a /usr/X11R6/lib/libXft.a /usr/X11R6/lib/libXrender.a \
		/usr/X11R6/lib/libX11.a /usr/X11R6/lib/libSM.a /usr/X11R6/lib/libICE.a\
		/usr/X11R6/lib/libXinerama.a /usr/X11R6/lib/libGL.a /usr/lib/libmng.a -lz -ljpeg

# Plugin based binary and its plugins

tora-plugin: \
	tora \
	plugins/toalert.tso \
	plugins/toanalyze.tso \
	plugins/tobrowser.tso \
	plugins/tocharts.tso \
	plugins/todebug.tso \
	plugins/tocurrent.tso \
	plugins/toextract.tso \
	plugins/toinvalid.tso \
	plugins/tooutput.tso \
	plugins/tooracleconnection.tso \
	plugins/toresult.tso \
	plugins/torollback.tso \
	plugins/toscript.tso \
	plugins/tosession.tso \
	plugins/tosecurity.tso \
	plugins/tosgatrace.tso \
	plugins/tosqledit.tso \
	plugins/tostorage.tso \
	plugins/tostoragedefinition.tso \
	plugins/totemplate.tso \
	plugins/totuning.tso \
	plugins/towidgets.tso \
	plugins/toworksheet.tso \
	$(MYSQL_PLUGIN)

# The binary for the pluginbased tora

tora: \
	objs/main.o \
	objs/toabout.o \
	objs/toaboutui.o \
	objs/tobackground.o \
	objs/toconnection.o \
	objs/todatabasesettingui.o \
	objs/toeditwidget.o \
	objs/toglobalsetting.o \
	objs/toglobalsettingui.o \
	objs/tohelp.o \
	objs/tohelpaddfileui.o \
	objs/tohelpsetupui.o \
	objs/tohighlightedtext.o \
	objs/tohtml.o \
	objs/tomain.o \
	objs/tomarkedtext.o \
	objs/tomessageui.o \
	objs/tomemoeditor.o \
	objs/tonewconnection.o \
	objs/tonewconnectionui.o \
	objs/tonoblockquery.o \
	objs/toparamget.o \
	objs/topreferences.o \
	objs/topreferencesui.o \
	objs/toresult.o \
	objs/toresultfield.o \
	objs/toresultitem.o \
	objs/toresultlistformatui.o \
	objs/toresultstats.o \
	objs/toresultview.o \
	objs/tosearchreplace.o \
	objs/tosearchreplaceui.o \
	objs/tosql.o \
	objs/tosyntaxsetup.o \
	objs/tosyntaxsetupui.o \
	objs/totemplateprovider.o \
	objs/tothread.o \
	objs/totool.o \
	objs/totoolsettingui.o \
	objs/utils.o
	@echo Linking $@
	$(GCC) $(LFLAGS) -Xlinker "--export-dynamic" $(LFLAGS_GLOB) \
		-o $@ $^ $(LIBS_GLOB) $(STDCPP_SHARED) $(QT_SHARED)

# This pretty requires a kdoc installtion and reference files for Qt and KDE Libs.
# configure won't try to detect those. It's up to you.

apidoc: $(API)
	mkdir -p help/api
	kdoc -n TOra -d help/api $^ -lqt -lkdeui -lkhtml
