Aggregate Functions:AVG ( DISTINCT|ALL expr )=Calculates the avarage value of <I>expr</I>.<P>\n<B>Example:</B><P>\nThis example calculates the average amount of all purchases.\n<PRE>\nSELECT AVG(amount) "Average" FROM purchase;\n\n   Average\n----------\n124144.619\n</PRE>
Aggregate Functions:CORR ( expr1 , expr2 )=
Aggregate Functions:COUNT ( *|DISTINCT|ALL expr )=
Aggregate Functions:COVAR_POP=
Aggregate Functions:COVAR_SAMP=
Aggregate Functions:GROUPING=
Aggregate Functions:MAX=
Aggregate Functions:MIN=
Aggregate Functions:REGR_AVGX=
Aggregate Functions:REGR_AVGY=
Aggregate Functions:REGR_COUNT=
Aggregate Functions:REGR_INTERCEPT=
Aggregate Functions:REGR_R2=
Aggregate Functions:REGR_SLOPE=
Aggregate Functions:REGR_SXX=
Aggregate Functions:REGR_SXY=
Aggregate Functions:REGR_SYY=
Aggregate Functions:STDDEV=
Aggregate Functions:STDDEV_POP=
Aggregate Functions:STDDEV_SAMP=
Aggregate Functions:SUM=
Aggregate Functions:VARIANCE=
Aggregate Functions:VAR_POP=
Aggregate Functions:VAR_SAMP=
Analytic Functions:AVG ( DISTINCT|ALL expr ) OVER ( analytic_clause )=
Analytic Functions:CORR ( expr1 , expr2 ) OVER ( analytic_clause )=
Analytic Functions:COUNT ( *|DISTINCT|ALL expr ) OVER ( analytic_clause )=
Analytic Functions:COVAR_POP=
Analytic Functions:COVAR_SAMP=
Analytic Functions:CUME_DIST=
Analytic Functions:DENSE_RANK=
Analytic Functions:FIRST_VALUE=
Analytic Functions:LAG=
Analytic Functions:LAST_VALUE=
Analytic Functions:LEAD=
Analytic Functions:MAX=
Analytic Functions:MIN=
Analytic Functions:NTILE=
Analytic Functions:PERCENT_RANK=
Analytic Functions:RANK=
Analytic Functions:RATIO_TO_REPORT=
Analytic Functions:REGR_AVGX=
Analytic Functions:REGR_AVGY=
Analytic Functions:REGR_COUNT=
Analytic Functions:REGR_INTERCEPT=
Analytic Functions:REGR_R2=
Analytic Functions:REGR_SLOPE=
Analytic Functions:REGR_SXX=
Analytic Functions:REGR_SXY=
Analytic Functions:REGR_SYY=
Analytic Functions:ROW_NUMBER=
Analytic Functions:STDDEV=
Analytic Functions:STDDEV_POP=
Analytic Functions:STDDEV_SAMP=
Analytic Functions:SUM=
Analytic Functions:VARIANCE=
Analytic Functions:VAR_POP=
Analytic Functions:VAR_SAMP=
Char to Char Functions:CHR ( n USING NCHAR_CS )=
Char to Char Functions:CONCAT ( char1 , char2 )=
Char to Char Functions:INITCAP=
Char to Char Functions:LOWER=
Char to Char Functions:LPAD=
Char to Char Functions:LTRIM=
Char to Char Functions:NLSSORT=
Char to Char Functions:NLS_INITCAP=
Char to Char Functions:NLS_LOWER=
Char to Char Functions:NLS_UPPER=
Char to Char Functions:REPLACE=
Char to Char Functions:RPAD=
Char to Char Functions:RTRIM=
Char to Char Functions:SOUNDEX=
Char to Char Functions:SUBSTR=
Char to Char Functions:SUBSTRB=
Char to Char Functions:TRANSLATE=
Char to Char Functions:TRIM=
Char to Char Functions:UPPER=
Char to Number Functions:ASCII ( char )=
Char to Number Functions:INSTR=
Char to Number Functions:INSTRB=
Char to Number Functions:LENGTH=
Char to Number Functions:LENGTHB=
Conversion Functions:CHARTOROWID ( char )=
Conversion Functions:CONVERT ( char , dest_char_set , source_char_set )=
Conversion Functions:HEXTORAW=
Conversion Functions:NUMTODSINTERVAL=
Conversion Functions:NUMTOYMINTERVAL=
Conversion Functions:RAWTOHEX=
Conversion Functions:ROWIDTOCHAR=
Conversion Functions:TO_CHAR(dateconversion)=
Conversion Functions:TO_CHAR(numberconversion)=
Conversion Functions:TO_DATE=
Conversion Functions:TO_LOB=
Conversion Functions:TO_MULTI_BYTE=
Conversion Functions:TO_NUMBER=
Conversion Functions:TO_SINGLE_BYTE=
Conversion Functions:TRANSLATE...USING=
Conversion Functions:Test=
Date Functions:ADD_MONTHS=
Date Functions:LAST_DAY=
Date Functions:MONTHS_BETWEEN=
Date Functions:NEW_TIME=
Date Functions:NEXT_DAY=
Date Functions:ROUND=
Date Functions:SYSDATE=
Date Functions:TRUNC=
Misc Single-Row Functions:BFILENAME ( ' directory ' , ' filename ' )=
Misc Single-Row Functions:DUMP=
Misc Single-Row Functions:EMPTY_BLOB=
Misc Single-Row Functions:EMPTY_CLOB=
Misc Single-Row Functions:GREATEST=
Misc Single-Row Functions:LEAST=
Misc Single-Row Functions:NLS_CHARSET_DECL_LEN=
Misc Single-Row Functions:NLS_CHARSET_ID=
Misc Single-Row Functions:NLS_CHARSET_NAME=
Misc Single-Row Functions:NVL=
Misc Single-Row Functions:NVL2=
Misc Single-Row Functions:SYS_CONTEXT=
Misc Single-Row Functions:SYS_GUID=
Misc Single-Row Functions:UID=
Misc Single-Row Functions:USER=
Misc Single-Row Functions:USERENV=
Misc Single-Row Functions:VSIZE=
Number functions:ABS ( n )=ABS returns the absolute value of <I>n</I>.<P>\n<B>Example:</B><P>\n<PRE>\nSELECT ABS(-20) "Absolute" FROM DUAL;\n\n  Absolute\n----------\n        20\n</PRE>
Number functions:ACOS ( n )=
Number functions:ADD_MONTHS ( d , n )=
Number functions:ASIN ( n )=
Number functions:ATAN ( n )=
Number functions:ATAN2 ( n , m )=
Number functions:BITAND ( argument1 , argument2 )=
Number functions:CEIL ( n )=
Number functions:COS ( n )=
Number functions:COSH ( n )=
Number functions:EXP=
Number functions:FLOOR=
Number functions:LN=
Number functions:LOG=
Number functions:MOD=
Number functions:POWER=
Number functions:ROUND=
Number functions:SIGN=
Number functions:SIN=
Number functions:SINH=
Number functions:SQRT=
Number functions:TAN=
Number functions:TANH=
Number functions:TRUNC=
Object Functions:DEREF=
Object Functions:MAKE_REF=
Object Functions:REF=
Object Functions:REFTOHEX=
Object Functions:VALUE=
