static const char *CopyrightText =     "<pre>\n"
    "TOra - An Oracle Toolkit for DBA's and developers\n"
    "\n"
    "Shared/mixed copyright is held throughout files in this product\n"
    "\n"
    "Portions Copyright (C) 2000-2001 Underscore AB\n"
    "Portions Copyright (C) 2003-2005 Quest Software, Inc.\n"
    "Portions Copyright (C) 2004-2008 Numerous Other Contributors\n"
    "\n"
    "This program is free software; you can redistribute it and/or\n"
    "modify it under the terms of the GNU General Public License\n"
    "as published by the Free Software Foundation;  only version 2 of\n"
    "the License is valid for this program.\n"
    "\n"
    "This program is distributed in the hope that it will be useful,\n"
    "but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
    "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
    "GNU General Public License for more details.\n"
    "\n"
    "You should have received a copy of the GNU General Public License\n"
    "along with this program; if not, write to the Free Software\n"
    "Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.\n"
    "\n"
    "     As a special exception, you have permission to link this program\n"
    "     with the Oracle Client libraries and distribute executables, as long\n"
    "     as you follow the requirements of the GNU GPL in regard to all of the\n"
    "     software in the executable aside from Oracle client libraries.\n"
    "\n"
    "     Specifically you are not permitted to link this program with the\n"
    "     Qt/UNIX, Qt/Windows or Qt Non Commercial products of TrollTech.\n"
    "     And you are not permitted to distribute binaries compiled against\n"
    "     these libraries. \n"
    "\n"
    "     You may link this product with any GPL'd Qt library.\n"
    "\n"
    "All trademarks belong to their respective owners.\n"
    "</pre>\n"
;
