
#pragma once

// QT headers first
#include <qapplication.h>
#include <qcheckbox.h>
#include <qclipboard.h>
#include <qcolordialog.h>
#include <qcombobox.h>
#include <qcursor.h>
#include <qdatetime.h>
#include <qdialog.h>
#include <qdir.h>
#include <qevent.h>
#include <qfile.h>
#include <qfileinfo.h>
#include <qfontdialog.h>
#include <qfont.h>
#include <qglobal.h>
#include <qinputdialog.h>
#include <qkeysequence.h>
#include <qlabel.h>
#include <qlayout.h>
#include <qlineedit.h>
#include <qmainwindow.h>
#include <qmenubar.h>
#include <qmessagebox.h>
#include <qmime.h>
#include <qmovie.h>
#include <qnamespace.h>
#include <qobject.h>
#include <qpainter.h>
#include <qpalette.h>
#include <qpixmap.h>
#include <qpoint.h>
#include <qprinter.h>
#include <qprogressdialog.h>
#include <qpushbutton.h>
#include <qradiobutton.h>
#include <qregexp.h>
#include <qsizepolicy.h>
#include <qspinbox.h>
#include <qsplitter.h>
#include <qsqldatabase.h>
#include <qsqlerror.h>
#include <qsqlfield.h>
#include <qsqlrecord.h>
#include <qsqlresult.h>
#include <qstatusbar.h>
#include <qstring.h>
#include <qstringlist.h>
#include <qstyle.h>
#include <qtabwidget.h>
#include <qtextcodec.h>
#include <qtimer.h>
#include <qtoolbar.h>
#include <qtoolbutton.h>
#include <qtooltip.h>
#include <qvalidator.h>
#include <qvariant.h>
#include <qwidget.h>

#include <QAbstractItemModel>
#include <QAbstractTableModel>
#include <QAction>
#include <QApplication>
#include <QBrush>
#include <QButtonGroup>
#include <QByteArray>
#include <QChar>
#include <QCheckBox>
#include <QClipboard>
#include <QCloseEvent>
#include <QColor>
#include <QColorGroup>
#include <QContextMenuEvent>
#include <QCoreApplication>
#include <QDataStream>
#include <QDateTime>
// #include <QDebug>
#include <QDesktopWidget>
#include <QDialog>
#include <QDialogButtonBox>
#include <QDir>
#include <QDockWidget>
#include <QDropEvent>
#include <QEvent>
#include <QFile>
#include <QFileDialog>
#include <QFileInfo>
#include <QFocusEvent>
#include <QFont>
#include <QFontMetrics>
#include <QFrame>
#include <QGridLayout>
#include <QGroupBox>
#include <QHBoxLayout>
#include <QHeaderView>
#include <QHideEvent>
#include <QIcon>
#include <QInputDialog>
#include <QItemDelegate>
#include <QKeyEvent>
#include <QLabel>
#include <QLineEdit>
#include <QList>
#include <QListWidget>
#include <QLocale>
#include <QMainWindow>
#include <QMap>
#include <QMdiArea>
#include <QMdiSubWindow>
#include <QMenu>
#include <QMessageBox>
#include <QMetaType>
#include <QMimeData>
#include <QModelIndex>
#include <QModelIndexList>
#include <QMouseEvent>
#include <QMutex>
#include <QMutexLocker>
#include <QObject>
#include <QPainter>
#include <QPaintEvent>
#include <QPalette>
#include <QPixmap>
#include <QPoint>
#include <QPointer>
#include <QPolygon>
#include <QPrintDialog>
#include <QProgressBar>
#include <QProgressDialog>
#include <QPushButton>
#include <QRect>
#include <QRegExp>
#include <QResizeEvent>
#include <QScrollArea>
#include <QScrollBar>
#include <QSettings>
#include <QShowEvent>
#include <QSize>
#include <QSortFilterProxyModel>
#include <QSpacerItem>
#include <QSplitter>
#include <QStackedWidget>
#include <QStatusBar>
#include <QString>
#include <QStringList>
#include <QStyle>
#include <QStyleFactory>
#include <QStyleOptionButton>
#include <QStylePainter>
#include <QTableView>
#include <QTabWidget>
#include <QTcpSocket>
#include <QtDebug>
#include <QTextBrowser>
#include <QTextCodec>
#include <QTextEdit>
#include <QTextStream>
#include <QtGlobal>
#include <QThread>
#include <QThreadStorage>
#include <QTimer>
#include <QTimerEvent>
#include <QToolBar>
#include <QToolButton>
#include <QTranslator>
#include <QTreeView>
#include <QTreeWidget>
#include <QTreeWidgetItem>
#include <QTreeWidgetItemIterator>
#include <QtSql>
#include <QVariant>
#include <QVBoxLayout>
#include <QVector>
#include <QWaitCondition>
#include <QWidget>

// STL headers
#include <algorithm>
#include <iostream>
#include <map>
#include <list>

// TOra headers
//#include "toresultview.h"
//#include "tomain.h"
//#include "tosql.h"
//#include "toconf.h"
//#include "totool.h"
//#include "toconnection.h"
//#include "utils.h"
//#include "config.h"
//#include "tologger.h"

