/* BEGIN_COMMON_COPYRIGHT_HEADER 
* END_COMMON_COPYRIGHT_HEADER */

#ifndef TOLISTVIEWFORMATTERIDENTIFIER_H
#define TOLISTVIEWFORMATTERIDENTIFIER_H

namespace toListViewFormatterIdentifier
{
enum { TEXT, TAB_DELIMITED, CSV, HTML, SQL};
}

#endif

